# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import processor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('keyPoint_1', models.IntegerField(default=0)),
                ('keyPoint_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('imageFile', models.ImageField(blank=True, default=None, height_field='height_field', null=True, upload_to=processor.models.PathAndRename('media'), width_field='width_field')),
                ('thumbnailImg', models.ImageField(blank=True, default=None, height_field='height_field', null=True, upload_to=processor.models.PathAndRename('projects'), width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
