# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='descriptor',
            field=models.ManyToManyField(to='processor.Descriptor'),
        ),
    ]
