# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_image_descriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='descriptor',
        ),
        migrations.AddField(
            model_name='image',
            name='hog_descriptor',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
