# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20170608_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
