# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_image_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='hog_descriptor',
        ),
    ]
