# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_remove_image_hog_descriptor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descriptor',
        ),
    ]
